# Generated by Django 4.2.16 on 2024-11-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_attendance_is_late"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="late_minutes",
            field=models.FloatField(default=0),
        ),
    ]
